use-sort:
    group:
        - _main
        - Jarvis
    group-type: each
    sort-type: alph
    sort-direction: asc

header: |
    /*
     * This file is part of the Jarvis package
     *
     * Copyright (c) 2015 Tony Dubreil
     *
     * For the full copyright and license information, please view the LICENSE
     * file that was distributed with this source code.
     *
     * Feel free to edit as you please, and have fun.
     *
     * @author Tony Dubreil <tonydubreil@gmail.com>
     */
